version: '3'
services:
  redis:
    image: redis:latest
    environment:
      - REDIS_HOST=redis-12686.c325.us-east-1-4.ec2.redns.redis-cloud.com
      - REDIS_PORT=12686
      - REDIS_PASSWORD=FU3MsSsInSR9MD759DJqBvTKumAJvXKG

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=transaction_analysis_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGODB_HOST=localhost
      - MONGODB_PORT=8080
      - MONGODB_DB=test
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AWS_HOSTNAME=https://mne2pdqrsc.execute-api.us-east-1.amazonaws.com/
      - CACHE_TOKEN=5D553D14CBA5C8D7F29A5A61AFEE3